name: 'Render Deployment Status Action'
description: 'Get a deployment status from your Render PR preview environment'
author: 'Anand Chowdhary <mail@anandchowdhary.com>'
inputs:
  render-api-key:
    required: true
    description: 'Render API key'
  github-token:
    required: true
    description: 'GitHub token'
    default: '${{ github.token }}'
runs:
  using: 'node16'
  main: 'dist/index.js'
